export const LOGIN_USER = 'LOGIN/LOGIN_USER';
export const LOGIN_USER_RESET = 'LOGIN/LOGIN_USER_RESET';
export const LOGIN_USER_SUCCESS = 'LOGIN/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN/LOGIN_USER_ERROR';