export const LOAD_POST_PAGE = 'POST_PAGE/LOAD_POST_PAGE';
export const LOAD_POST_PAGE_SUCCESS = 'POST_PAGE/LOAD_POST_PAGE_SUCCESS';
export const LOAD_POST_PAGE_ERROR = 'POST_PAGE/LOAD_POST_PAGE_ERROR';