export const GET_PROFILE = 'PROFILE/GET_PROFILE';
export const GET_PROFILE_RESET = 'PROFILE/GET_PROFILE_RESET';
export const GET_PROFILE_SUCCESS = 'PROFILE/GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'PROFILE/GET_PROFILE_ERROR';