export const ADD_USER = 'REGISTRATION/ADD_USER';
export const ADD_USER_RESET = 'REGISTRATION/ADD_USER_RESET';
export const ADD_USER_SUCCESS = 'REGISTRATION/ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'REGISTRATION/ADD_USER_ERROR';